### PR TITLE
Changed the tier tiles to use a tabbed view.

### PR DESCRIPTION
**Pull request by Randy808**
I changed the styling of the tiers. Feel free to close the PR if you don't like the changes

tab view

https://github.com/LiranCohen/btc-grove-site/assets/4742100/d97efab8-02ae-4959-9ce1-dc4cd1c4f472

### CODE REVIEW

**Comment by Randy808** [comment]
The goal was to add a picture to the right of the tier description but I don't have any good quality pics of the grove lol

So closer to something like this (disregard the green tab underline, the light font-weight, and any other changes not in this PR):
Screenshot 2023-05-16 at 9 07 51 AM

**Comment by LiranCohen** [comment]
Ah dude!!! This is awesome! I'm gonna take a look and merge it in.

My design skills are crap but I figure we will post this up on the btc grove github and also have anyone else contribute.

**Comment by LiranCohen** [comment]
I don't think I can push to your repo, but I rebased it and made some styling adjustments, and added some temp photos.

Still needs a lot of work on the styling lol, CSS and design is not a muscle i exercise often enough... but I like the direction.

Take a look and rebase your branch to include this and see if you want to make any other changes to make it look a little better.

**Comment by Randy808** [comment]
Updated 🚀


https://github.com/LiranCohen/btc-grove-site/assets/4742100/20b9f00e-0271-489b-85ce-a4a4bd478ac5

**Pull request merged**
